### PR TITLE
Updated sti with jboss userid and usage script

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dsimansk** [comment]
@rhuss @dhirajsb hi guys. I've just noticed the user id isn't numeric as required by OSE s2i.

**Comment by dhirajsb** [comment]
@dsimansky i ran into an issue with using numeric ids, looked like the ids
were not what i was expecting, need to revisit that, but it seems to be
working ok for now.

**Comment by dsimansk** [comment]
@dhirajsb I'm seeing the same error as I've described here https://github.com/fabric8io/base-images/issues/1

**Comment by dhirajsb** [comment]
@dsimansk I've fixed the s2i builder to use a numeric id.

**Pull request merged**
